### ISSUE TITLE
links to mailing list broken

### ISSUE THREAD

**Issue by boombatower** [boombatower/tumbleweed-review#10]
Based on #9 link generation to mailing list threads is broken since the URLs are not generated in a predictable manor nor are the `Archived-At` headers included in the mailbox download. The best solution would be for upstream to include the headers as setting up a email subscription and downloading all mail to get the headers is more work and maintenance plus missing the period until it is setup.

**Comment by tvogel** [comment]
The review page still links emails here. So, is this is issue fixed such that the links could be generated correctly again or rather not?

**Comment by boombatower** [comment]
Downloading the mailing list archives to read the emails is restored, but the archive lost the information needed to generate a URL to view the mail from the web. So while the email subjects can be displayed after parsing the replies and bodies a link to the mail cannot.

**Comment by doenietzomoeilijk** [comment]
Actually, the URL *is* predictable. It's generated [here](https://gitlab.com/mailman/hyperkitty/-/blob/201b5d350253c7866097602e305e580ad4d50d50/hyperkitty/lib/utils.py#L48), and simply consists of the base32-encoded SHA-1 hash of the e-mail message-ID - which, I think, should be in the inbox.

The latest snapshot at this moment is 20210613, and the announcement e-mail lives [here](https://lists.opensuse.org/archives/list/factory@lists.opensuse.org/thread/ECUAOSYLLWKLG5AL3QGMCQ3AXP3FKQYY/). When I download that message, I get an e-mail with `Message-ID: <162371163727.3077.18028238154166268965@go-agent-stagingbot-6>`. If I run this line in a Python interpreter:

```python
b32encode(sha1("162371163727.3077.18028238154166268965@go-agent-stagingbot-6").digest()).decode('utf-8')
```
...then sure enough, the answer is `u'ECUAOSYLLWKLG5AL3QGMCQ3AXP3FKQYY'`, which is the dynamic bit in that mailing list URL.

So. I'm a bit rusty in Python, but I *could* try my hand at making this work in the current code; if somebody who has the actual code checked out and the whole mail thing set up to give it a go, that's fine too, but unless the MSGID changes from the mailing list to the download, it should be possible to predict the mailing list URL.
