### ISSUE TITLE
gcc version report

### ISSUE THREAD

**Issue by bdamascen0** [boombatower/tumbleweed-review#15]
The quick binary version table isn't reporting gcc11 that was added at snapshot 2021-02-05.

Example:
Snapshot 2021-02-12 has gcc11-11.0.0+git183291-1.1 and gcc-10-3.2 but the table shows:

Binary | Version
gcc | 10
gcc7 | 7.5.0+r278197
gcc9 | 9.3.1+git1684

**Comment by boombatower** [comment]
42aa7cd7716e0577c1f5fea549d48f375e913ab8 should do it.

**Comment by boombatower** [comment]
Should be automatically resolved in the future by 93d59f93f41e1600ce4c06d1f6cdeb291a88be94.
