### ISSUE TITLE
Add xwayland to quick table

### ISSUE THREAD

**Issue by bdamascen0** [boombatower/tumbleweed-review#16]
Update the graphic stack on quick table to keep track of Xwayland standalone package.
(https://fedoraproject.org/wiki/Changes/XwaylandStandalone)
(https://lists.x.org/archives/xorg-announce/2021-March/003076.html)
(https://build.opensuse.org/request/show/885118)

The Xwayland standalone package is available on tumbleweed since snapshot 20210414.
(http://download.opensuse.org/history/20210414/rpm.unique.list)

**Comment by boombatower** [comment]
Fixed by e47f20fd84d65c500246cda2d82512055f7dfae1.
